name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # попробую новую версию
    steps:
      - uses: actions/checkout@v4          # вместо v3
      - name: Use Node.js
        uses: actions/setup-node@v4        # вместо v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test
      - run: npx eslint src
      - run: npm run build                  # если есть скрипт сборки